language: c
script: asdf plugin test ruby . --asdf-plugin-gitref $TRAVIS_BRANCH ruby -v
before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export TRUFFLERUBY_RECOMPILE_OPENSSL=false; fi
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
